site_name: Language Learning
theme:
  name: material
  footer:
    hide: true
  font:
    # text: JetBrains Mono
    text: Nunito
    code: Space Mono
  logo: assets/lang.svg
  favicon: assets/favicon.ico
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

      icon:
        repo: fontawesome/brands/github

  features:
    - navigation.footer
    - navigation.instant
    - search.suggest
    - search.highlighting

  # favicon: img/favicon.png
  # logo: img/moe.svg
  # icon:
  #   repo: fontawesome/brands/github

nav:
  - Главная: "index.md" # Главная страница
  - "Корейский язык": # Раздел "Guides"
      - "Корейский Алфавит": "korean/alphabet.md" # Страница "Japanese Guide"
  - "Японский язык": # Раздел "Visual Novels"
      - "Японский Алфавит": "japanese/alphabet.md"
      - "Падежи": "japanese/cases.md"
      - "Порядок слов": "japanese/word_order.md"
      - "Предлоги": "japanese/prepositions.md"
      # - "Слова-связки": "japanese/linking_words.md"
      - "Глаголы": "japanese/verbs.md"
      - "Прилагательные": "japanese/adjectives.md"
  - "Немецкий язык":
      - "А1":
          - "Алфавит": "german/a1/alphabet.md"
          - "Базовая грамматика": "german/a1/basic_grammar.md"
          - "Местоимения": "german/a1/pronouns.md"
          - "Артикли": "german/a1/articles.md"
          - "Глаголы и спряжение в настоящем времени": "german/a1/verbs.md"
          - "Простые предложения и вопросы": "german/a1/simple_sentences.md"
          - "Числа, цвета, дни недели и базовая лексика": "german/a1/vocabulary.md"
          - "Предлоги места и времени": "german/a1/prepositions.md"
          - "Порядок слов в предложении (расширенный)": "german/a1/word_order(extended).md"
          - "Модальные глаголы": "german/a1/modal_verbs.md"
          - "Прошедшее время (Perfekt)": "german/a1/past_perfect.md"
          - "Прилагательные и их склонение": "german/a1/adjectives.md"
      - "А2":
          - "Местоимения в косвенных падежах (Dativ, Akkusativ)": "german/a2/pronouns_in_oblique_cases.md"
          - "Предлоги с управлением падежей (Dativ, Akkusativ)": "german/a2/prepositions_with_case_control.md"
          - "Сложные прошедшие времена (Präteritum, Perfekt в деталях)": "german/a2/complicated_past_tenses.md"
          - "Притяжательные местоимения (Possessivpronomen)": "german/a2/possessive_pronouns.md"
          - "Порядок слов в придаточных предложениях": "german/a2/word_order_in_subordinate_clauses.md"
          - "Склонение прилагательных с артиклями": "german/a2/declension_of_adjectives_with_articles.md"
          - "Местоимения в Dativ и Akkusativ": "german/a2/pronouns_in_dativ_and_akku.md"
          - "Сравнительная и превосходная степень прилагательных (größer, am größten)": "german/a2/comparative_and_superlative_degrees.md"
          - "Повелительное наклонение (Mach das! Helft mir!)": "german/a2/imperative.md"
          - "Разделительные глаголы (Trennbare Verben) и неразделимые (aufstehen, besuchen и т.п.)": "german/a2/separable_inseparable_verbs.md"
          - "Употребление двойных союзов (z.B. nicht nur, sondern auch...)": "german/a2/double_conjuctions.md"
          - "Perfekt с модальными глаголами (Ich habe arbeiten müssen)": "german/a2/imperative.md"
          

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/likeauser9
    - icon: material/email
      link: mailto:frdwoz5@gmail.com
    - icon: material/web
      link: https://yourwebsite.com

# extra_css:
#   - assets/stylesheets/extra.css

# extra_javascript:
#   - https://kit.fontawesome.com/8bdf8c69c6.js

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

  - admonition
  - pymdownx.details
